### ISSUE TITLE
Serial Inject GPS (from ctrl-f menu) fails after a few seconds.

### ISSUE THREAD

**Issue by denniszollo** [diydrones/MissionPlanner#1049]
Serial Inject GPS often fails after a few seconds of forwarding observations.  This is in the UDP Host configuration with any baudrate selected.    This has been observed both with mission planner 1.3.31 and 1.3.32.  

I haven't tracked down the error exactly, but the following have been observed in the Mission Planner log.It is hard to tell when the line in the log comes from pressing the "stop" button after the forwarding has stopped or when the forwarding stopped.

33:05,458 ERROR MissionPlanner.SerialInjectGPS - System.NullReferenceException: Object reference not set to an instance of an object.
   at MissionPlanner.Comms.UdpSerial.get_BytesToRead() in c:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Comms\CommsUdpSerial.cs:line 57
   at MissionPlanner.SerialInjectGPS.mainloop() in c:\Users\michael\Source\Repos\MissionPlanner\SerialInjectGPS.cs:line 125 (c:\Users\michael\Source\Repos\MissionPlanner\SerialInjectGPS.cs:136) [injectgps]

2015-10-29 17:54:25,476  INFO MissionPlanner.Comms.UdpSerial - NetSerial connecting to 127.0.0.1 : 54211 (c:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Comms\CommsUdpSerial.cs:148) [ProgressReporterDialogue Background thread]
2015-10-29 17:54:25,476  INFO MissionPlanner.Controls.ProgressReporterDialogue - DoWork Done (c:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Controls\ProgressReporterDialogue.cs:107) [ProgressReporterDialogue Background thread]

5-10-29 17:52:09,997 ERROR MissionPlanner.SerialInjectGPS - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.get_Available()
   at MissionPlanner.Comms.UdpSerial.get_BytesToRead() in c:\Users\michael\Source\Repos\MissionPlanner\ExtLibs\Comms\CommsUdpSerial.cs:line 57
   at MissionPlanner.SerialInjectGPS.mainloop() in c:\Users\michael\Source\Repos\MissionPlanner\SerialInjectGPS.cs:line 125 (c:\Users\michael\Source\Repos\MissionPlanner\SerialInjectGPS.cs:136) [injectgps]

**Comment by denniszollo** [comment]
One entire log where the issue occurred available here.

**Comment by meee1** [comment]
what is you testing enviroment?

ie I assume piksi console? using the udp?

can you provide some more info so I can replicate.

**Comment by denniszollo** [comment]
The setup basically follows the WIKI page I wrote, which worked as of July and is availble here: http://docs.swiftnav.com/wiki/Integrating_Piksi_with_the_Pixhawk_platform

Here are the cliffnotes:
Intel MAC running windows natively
Piksi Console forwarding observations over UDP
Mission planner set up as UDP host
Connect to Pixhawk over USB in Mission Planner
Piksi GPS device attached to Pixhawk over Serial 4/5 @115200 baud

Do you require a simulator of the UDP traffic?  I can spin one up for you.

**Comment by meee1** [comment]
dennis, could you try MP beta?
looks like it might have been a udp circle buffer bug.

**Comment by denniszollo** [comment]
MP Beta seems to have done the trick, It has run continuously for many minutes.
